name: jsoncheck

permissions:
  statuses: write

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check JSON syntax
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"

      - name: Update success status
        if: success()
        run : |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state='success' \
          -f context='json' \
        env:
          GH_TOKEN: ${{ github.token }}

      - name: update failed status
        if: failure()
        run : |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state='failure' \
          -f context='json' \
        env:
          GH_TOKEN: ${{ github.token }}
